version: '3.3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-fo
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "food_order"
    ports:
      - "5454:5432"